(function(){function h(){}function m(a,b,c){this.g=0;this.f="";this.S=12;this.L=3.5;this.I=16;this.b="cfhistuCFHISTU";this.a="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";this.u="";null!=a&&(this.u=a);null!=c&&(this.a=c);a="";c=0;for(var d=this.a.length;c<d;){var e=c++;-1==a.indexOf(this.a.charAt(e))&&(a+=this.a.charAt(e))}this.a=a;this.g=0<h.j(""+b)?b:0;if(this.a.length<this.I)throw new g("error: alphabet must contain at least "+this.I+" unique characters");if(-1<this.a.indexOf(" "))throw new g("error: alphabet cannot contain spaces");
b=0;for(a=this.b.length;b<a;)c=b++,d=this.a.indexOf(this.b.charAt(c)),-1==d?this.b=this.b.substring(0,c)+" "+this.b.substring(c+1):this.a=this.a.substring(0,d)+" "+this.a.substring(d+1);this.a=this.a.replace(RegExp(" ","g"),"");this.b=this.b.replace(RegExp(" ","g"),"");this.b=this.l(this.b,this.u);if(0<this.b.length||this.a.length/this.b.length>this.L)b=Math.ceil(this.a.length/this.L),1==b&&++b,b>this.b.length?(b-=this.b.length,this.b+=f.substr(this.a,0,b),this.a=f.substr(this.a,b,null)):this.b=f.substr(this.b,
0,b);this.a=this.l(this.a,this.u);b=Math.ceil(this.a.length/this.S);3>this.a.length?(this.f=f.substr(this.b,0,b),this.b=f.substr(this.b,b,null)):(this.f=f.substr(this.a,0,b),this.a=f.substr(this.a,b,null))}function g(a){this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,g)}function n(){this.o={}}function f(){}function k(){this.hash=new m;this.H="hx";this.self=null;this.uid=this.G="";this.total=this.s=0;this.local=window.document.currentScript.ownerDocument;this.i=this.local.querySelector("template");
var a=this.i.hasAttribute("data-prefix");1==this.i.hasAttribute("data-name")&&(a&&(this.H=this.i.getAttribute("data-prefix")),this.G=""+this.H+"-"+this.i.getAttribute("data-name"),null==this.self&&(this.self=this),this.register())}function q(a,b){function c(){}c.prototype=a;var d=new c,e;for(e in b)d[e]=b[e];b.toString!==Object.prototype.toString&&(d.toString=b.toString);return d}function t(a,b){if(null==b)return null;null==b.v&&(b.v=u++);var c;null==a.w?a.w={}:c=a.w[b.v];null==c&&(c=function(){return c.method.apply(c.scope,
arguments)},c.scope=a,c.method=b,a.w[b.v]=c);return c}k.P=function(){new k};k.aa=HTMLElement;k.prototype=q(HTMLElement.prototype,{m:function(){if(null==this.D){var a=new n,b=t(this,this.check);null!=r.Z?a.W("DOMCustomElementFinished",b):a.o.DOMCustomElementFinished=b;this.D=a}return this.D},register:function(){null!=this.self&&window.document.registerElement(""+this.G,{prototype:this.self})},Y:function(a){var b="";if(3==a.nodeType)b=a.textContent;else if(8!=a.nodeType){for(var b=[],c=0,d=a.attributes;c<
d.length;){var e=d[c];++c;"uid"!=e.name&&b.push(e.name+e.value)}a=a.nodeName+b.join("")+a.querySelectorAll("*").length;b=[];c=0;for(d=a.length;c<d;)e=c++,b.push(f.c(a,e));b=this.hash.encode(b)}return b},createdCallback:function(){this.setAttribute("uid",this.uid=this.Y(this));var a=this.i.content;this.root=this.createShadowRoot();this.root.appendChild(window.document.importNode(a,!0))},X:function(){for(var a=this.root.querySelectorAll("content"),b=0,c=a.length;b<c;){var d=b++;a[d].setAttribute("uid",
""+this.uid+"."+d)}},U:function(){for(var a=this.m().keys();a.F();){var b=a.next();this.addEventListener(b,this.m().get(b))}},attachedCallback:function(){this.X();var a=this.querySelectorAll(":root > [uid]:not(content)");this.s=this.total=a.length;0<a.length?this.U():this.J()},check:function(a){null!=a&&(a.stopPropagation(),--this.s);0==this.s&&this.J()},K:function(){for(var a=this.m().keys();a.F();){var b=a.next();this.removeEventListener(b,this.m().get(b))}},detachedCallback:function(){this.K()},
done:function(){this.K();this.dispatchEvent(new CustomEvent("DOMCustomElementFinished",{detail:this.uid,bubbles:!0,cancelable:!0}))},T:function(){for(var a=this.parentElement,b=this.root.children,c=0;c<b.length;){var d=b[c];++c;for(var e=a.nodeName+" > "+d.nodeName,f=[],g=0,h=d.attributes;g<h.length;){var l=h[g];++g;f.push("["+l.name+'="'+l.value+'"]')}0==a.querySelectorAll(e+f.join("")).length&&a.insertBefore(this.local.importNode(d,!0),this)}a=this.root.querySelectorAll("content");for(b=0;b<a.length;)if(c=
a[b],++b,d=c.getAttribute("uid"),c=c.getDistributedNodes(),d=window.document.querySelectorAll('[uid="'+d+'"]')[0])for(e=0;e<c.length;)f=c[e],++e,d.parentElement.insertBefore(window.document.importNode(f,!0),d)},J:function(){this.T();-1<this.total&&(this.done(),this.s=this.total=-1,this.V())},V:function(){var a=window.document.querySelector('[uid="'+this.uid+'"]');null!=a&&a.parentNode.removeChild(a)}});f.c=function(a,b){var c=a.charCodeAt(b);return c!=c?void 0:c};f.substr=function(a,b,c){if(null==
c)c=a.length;else if(0>c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};f.O=function(a){return{C:0,A:a,F:function(){return this.C<this.A.length},next:function(){return this.A[this.C++]}}};n.$=[function(){}];n.prototype={get:function(a){return null!=r[a]?this.R(a):this.o[a]},W:function(a,b){null==this.h&&(this.h={});this.h["$"+a]=b},R:function(a){return null==this.h?null:this.h["$"+a]},keys:function(){return f.O(this.N())},N:function(){var a=[],b;for(b in this.o)this.o.hasOwnProperty(b)&&
a.push(b);if(null!=this.h)for(b in this.h)36==b.charCodeAt(0)&&a.push(b.substr(1));return a}};g.j=function(a){return a instanceof Error?a:new g(a)};g.c=Error;g.prototype=q(Error.prototype,{});m.prototype={l:function(a,b){if(null==b)return a;for(var c=a.length-1,d=0,e=0,g,h;0<c;)d%=b.length,g=f.c(b.charAt(d),0),e+=g,g=(g+d+e)%c,h=a.charAt(g),a=f.substr(a,0,g)+a.charAt(c)+f.substr(a,g+1,null),a=f.substr(a,0,c)+h+f.substr(a,c+1,null),--c,++d;return a},encode:function(a){if(0==a.length)return"";for(var b=
0,c=a.length;b<c;){var d=b++;if(0!=a[d]%1||0>a[d])return""}return this.M(a)},M:function(a){for(var b=0,c=a.length,d=0,e=a.length;d<e;)var g=d++,b=b+a[g]%(g+100);for(var e=this.a,g=d=e.charAt(b%e.length),k=0,n=a.length;k<n;){var l=k++,p=a[l],e=this.l(e,f.substr(""+g+this.u+e,0,e.length)),m=this.hash(p,e),d=d+m;l+1<c&&(p%=f.c(m,0)+l,d+=this.b.charAt(p%this.b.length))}d.length<this.g&&(a=(b+f.c(d,0))%this.f.length,a=this.f.charAt(a),d=a+d,d.length<this.g&&(a=(b+f.c(d,2))%this.f.length,a=this.f.charAt(a),
d+=a));for(b=h.j(""+e.length/2);d.length<this.g;)e=this.l(e,e),d=f.substr(e,b,null)+d+f.substr(e,0,b),a=d.length-this.g,0<a&&(d=f.substr(d,a/2|0,this.g));return d},hash:function(a,b){for(var c="";null!=a&&0<a;)c=b.charAt(a%b.length)+c,a=h.j(""+a/b.length);return c}};h.toString=function(a,b){null==b&&(b=10);if(2>b||b>h.B.length)throw new g("Unsupported radix "+b);return a.toString(b)};h.j=function(a){if(10>h.B.length)throw new g("Unsupported radix 10");a=parseInt(a,10);return isNaN(a)?null:a};var u=
0,r={};h.B="0123456789abcdefghijklmnopqrstuvwxyz";k.P()})();
